version: "3.9"

services:
  frontend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - SHARED_PASSWORD=${SHARED_PASSWORD}
      - NODE_ENV=production
